### ISSUE TITLE
Problem for training 

### ISSUE THREAD

**Issue by nto4** [shivammehta25/Matcha-TTS#10]
Hi, im trying to train that model ım download dataset LJSpeech-1.1  for testing and understand training part ım try to train that model using this date
ım split metadat.csv last 500 line will be  ljs_audio_text_val_filelist.txt rest of it  ljs_audio_text_train_filelist.txt 
and my wavs directory containing audios in same directory like this 
```

(matcha-tts-sourceenv) root@DESKTOP-RUI9N9R:/matcha-tts-source/Matcha-TTS/data/filelists# ll
total 1908
drwxr-xr-x 3 root   root      4096 Sep 27 19:59 ./
drwxr-xr-x 4 root   root      4096 Sep 27 15:05 ../
-rw-r--r-- 1 root   root   1407640 Sep 27 20:03 ljs_audio_text_train_filelist.txt
-rw-r--r-- 1 root   root     58269 Sep 27 20:03 ljs_audio_text_val_filelist.txt
drwxr-xr-x 2 mehmet mehmet  471040 Feb 19  2018 wavs/

```

and my txts are looks like this im removed after | chracter and also that chracter because of torctron2 guide say this it is correct ı hope ? 

```
LJ001-0001|Printing, in the only sense with which we are at present concerned, differs from most if not from all the arts and crafts represented in the Exhibition
LJ001-0002|in being comparatively modern.

```

when ım try run this command  im received runtime error what im  doing wrong can u explain me ? 
```


(matcha-tts-sourceenv) root@DESKTOP-RUI9N9R:/matcha-tts-source/Matcha-TTS/data/filelists# matcha-data-stats -i ljspeech.yaml
Traceback (most recent call last):                                                                                                                                                   
  File "/root/anaconda3/envs/matcha-tts-sourceenv/bin/matcha-data-stats", line 8, in <module>
    sys.exit(main())
  File "/matcha-tts-source/Matcha-TTS/matcha/utils/generate_data_statistics.py", line 102, in main
    params = compute_data_statistics(data_loader, cfg["n_feats"])
  File "/matcha-tts-source/Matcha-TTS/matcha/utils/generate_data_statistics.py", line 36, in compute_data_statistics
    for batch in tqdm(data_loader, leave=False):
  File "/root/anaconda3/envs/matcha-tts-sourceenv/lib/python3.10/site-packages/tqdm/std.py", line 1182, in __iter__
    for obj in iterable:
  File "/root/anaconda3/envs/matcha-tts-sourceenv/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
  File "/root/anaconda3/envs/matcha-tts-sourceenv/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "/root/anaconda3/envs/matcha-tts-sourceenv/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/root/anaconda3/envs/matcha-tts-sourceenv/lib/python3.10/site-packages/torch/_utils.py", line 644, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/root/anaconda3/envs/matcha-tts-sourceenv/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/root/anaconda3/envs/matcha-tts-sourceenv/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/anaconda3/envs/matcha-tts-sourceenv/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/matcha-tts-source/Matcha-TTS/matcha/data/text_mel_datamodule.py", line 197, in __getitem__
    datapoint = self.get_datapoint(self.filepaths_and_text[index])
  File "/matcha-tts-source/Matcha-TTS/matcha/data/text_mel_datamodule.py", line 168, in get_datapoint
    mel = self.get_mel(filepath)
  File "/matcha-tts-source/Matcha-TTS/matcha/data/text_mel_datamodule.py", line 173, in get_mel
    audio, sr = ta.load(filepath)
  File "/root/anaconda3/envs/matcha-tts-sourceenv/lib/python3.10/site-packages/torchaudio/backend/sox_io_backend.py", line 256, in load
    return _fallback_load(filepath, frame_offset, num_frames, normalize, channels_first, format)
  File "/root/anaconda3/envs/matcha-tts-sourceenv/lib/python3.10/site-packages/torchaudio/backend/sox_io_backend.py", line 30, in _fail_load
    raise RuntimeError("Failed to load audio from {}".format(filepath))
RuntimeError: Failed to load audio from LJ031-0079
```

if you need another details or anythink just message ı will provide and thanks alot for helping.

**Comment by shivammehta25** [comment]
Hi! 
The audio file should have `.wav` as an extension. [Please take a look at the file lists of Tacotron 2.](https://github.com/NVIDIA/tacotron2/blob/master/filelists/ljs_audio_text_test_filelist.txt)  You can follow the instructions given there for the same. 
The file list for 🍵 Matcha-TTS is the same at least for a single speaker.

```
first_fileloc.wav|text1
second_fileloc.wav|text2
```

**Comment by nto4** [comment]
my second question on matcha-tts can possible one shot learning or transfer learning ım mean if i can suploy much leeser samples than espeak foreaxmple only 5 minute sample or just one sample can create audio using that speark voice im mean voice clonning is it possible on that model

**Comment by shivammehta25** [comment]
Unfortunately no, It is just for text-to-speech, it is not a voice cloning tool. So, you need to train with a larger amount of data to synthesise a speaker's voice.

**Comment by shivammehta25** [comment]
I am closing this issue for now, it seems to be resolved, feel free to reopen incase you have more questions.

**Comment by nto4** [comment]
thank you for your explanation
