### ISSUE TITLE
Generating normalization statistics error

### ISSUE THREAD

**Issue by effusiveperiscope** [shivammehta25/Matcha-TTS#11]
Hello, 

When generating normalization statistics as directed in the README I get the following error:
```
Traceback (most recent call last):
  File "C:\Users\vul\miniconda3\envs\matcha-tts\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\vul\miniconda3\envs\matcha-tts\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\vul\miniconda3\envs\matcha-tts\Scripts\matcha-data-stats.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "D:\Code\Matcha-TTS\matcha\utils\generate_data_statistics.py", line 102, in main
    params = compute_data_statistics(data_loader, cfg["n_feats"])
  File "D:\Code\Matcha-TTS\matcha\utils\generate_data_statistics.py", line 36, in compute_data_statistics
    for batch in tqdm(data_loader, leave=False):
  File "C:\Users\vul\miniconda3\envs\matcha-tts\lib\site-packages\tqdm\std.py", line 1182, in __iter__
    for obj in iterable:
  File "C:\Users\vul\miniconda3\envs\matcha-tts\lib\site-packages\torch\utils\data\dataloader.py", line 633, in __next__    data = self._next_data()
  File "C:\Users\vul\miniconda3\envs\matcha-tts\lib\site-packages\torch\utils\data\dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "C:\Users\vul\miniconda3\envs\matcha-tts\lib\site-packages\torch\utils\data\dataloader.py", line 1371, in _process_data
    data.reraise()
  File "C:\Users\vul\miniconda3\envs\matcha-tts\lib\site-packages\torch\_utils.py", line 644, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 4.
Original Traceback (most recent call last):
  File "C:\Users\vul\miniconda3\envs\matcha-tts\lib\site-packages\torch\utils\data\_utils\worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Users\vul\miniconda3\envs\matcha-tts\lib\site-packages\torch\utils\data\_utils\fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "D:\Code\Matcha-TTS\matcha\data\text_mel_datamodule.py", line 223, in __call__
    y[i, :, : y_.shape[-1]] = y_
RuntimeError: expand(torch.FloatTensor{[2, 80, 293]}, size=[80, 293]): the number of sizes provided (2) must be greater or equal to the number of dimensions in the tensor (3)

```

Do you know what might have caused this?

**Comment by shivammehta25** [comment]
The file in question here is a stereo channel audio. `torch.FloatTensor{[2, 80, 293]}`. Take a look at its first dimension, it should be `1`, so, you need to convert all files to monochannel first. 

You can simply run a sox command for it: `sox in.wav -c 1 out.wav`

**Comment by shivammehta25** [comment]
I am assuming this is fixed as I haven't heard back from you. I am closing it for now, feel free to reopen in case of further questions.

**Comment by effusiveperiscope** [comment]
OK thanks
