### ISSUE TITLE
cannot resume training

### ISSUE THREAD

**Issue by eschmidbauer** [shivammehta25/Matcha-TTS#20]
Trying to resume training, it runs for a bit, and then errors as follows:
```
Trainable params: 18.2 M
Non-trainable params: 0
Total params: 18.2 M
Total estimated model params size (MB): 72
Restored all states from the checkpoint at models/libritts-r-run/checkpoints/last.ckpt
/home/myuser/miniconda3/envs/Matcha-TTS/lib/python3.11/site-packages/torch/nn/modules/conv.py:309: UserWarning: Applied workaround for CuDNN issue, install nvrtc.so (Triggered
internally at ../aten/src/ATen/native/cudnn/Conv_v8.cpp:80.)
  return F.conv1d(input, weight, bias, self.stride,
/home/myuser/miniconda3/envs/Matcha-TTS/lib/python3.11/site-packages/lightning/pytorch/utilities/data.py:76: UserWarning: Trying to infer the `batch_size` from an
ambiguous collection. The batch size we found is 8. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
  warning_cache.warn(
Epoch 84/-2 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23089/23089 1:58:45 • 0:00:00 3.57it/s v_num: 0 loss/train_step: nan loss/val_step: nan loss/val_epoch: nan
[2023-10-17 17:35:25,842][matcha.utils.utils][ERROR] -
Traceback (most recent call last):
  File "/home/myuser/Matcha-TTS/matcha/utils/utils.py", line 76, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
                               ^^^^^^^^^^^^^^^^^^
  File "/home/myuser/Matcha-TTS/matcha/train.py", line 79, in train
    trainer.fit(model=model, datamodule=datamodule, ckpt_path=cfg.get("ckpt_path"))
  File "/home/myuser/miniconda3/envs/Matcha-TTS/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 532, in fit
    call._call_and_handle_interrupt(
  File "/home/myuser/miniconda3/envs/Matcha-TTS/lib/python3.11/site-packages/lightning/pytorch/trainer/call.py", line 43, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myuser/miniconda3/envs/Matcha-TTS/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 571, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/myuser/miniconda3/envs/Matcha-TTS/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 980, in _run
    results = self._run_stage()
              ^^^^^^^^^^^^^^^^^
  File "/home/myuser/miniconda3/envs/Matcha-TTS/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 1023, in _run_stage
    self.fit_loop.run()
  File "/home/myuser/miniconda3/envs/Matcha-TTS/lib/python3.11/site-packages/lightning/pytorch/loops/fit_loop.py", line 202, in run
    self.advance()
  File "/home/myuser/miniconda3/envs/Matcha-TTS/lib/python3.11/site-packages/lightning/pytorch/loops/fit_loop.py", line 355, in advance
    self.epoch_loop.run(self._data_fetcher)
  File "/home/myuser/miniconda3/envs/Matcha-TTS/lib/python3.11/site-packages/lightning/pytorch/loops/training_epoch_loop.py", line 134, in run
    self.on_advance_end()
  File "/home/myuser/miniconda3/envs/Matcha-TTS/lib/python3.11/site-packages/lightning/pytorch/loops/training_epoch_loop.py", line 249, in on_advance_end
    self.val_loop.run()
  File "/home/myuser/miniconda3/envs/Matcha-TTS/lib/python3.11/site-packages/lightning/pytorch/loops/utilities.py", line 181, in _decorator
    return loop_run(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myuser/miniconda3/envs/Matcha-TTS/lib/python3.11/site-packages/lightning/pytorch/loops/evaluation_loop.py", line 122, in run
    return self.on_run_end()
           ^^^^^^^^^^^^^^^^^
  File "/home/myuser/miniconda3/envs/Matcha-TTS/lib/python3.11/site-packages/lightning/pytorch/loops/evaluation_loop.py", line 258, in on_run_end
    self._on_evaluation_end()
  File "/home/myuser/miniconda3/envs/Matcha-TTS/lib/python3.11/site-packages/lightning/pytorch/loops/evaluation_loop.py", line 304, in _on_evaluation_end
    call._call_lightning_module_hook(trainer, hook_name, *args, **kwargs)
  File "/home/myuser/miniconda3/envs/Matcha-TTS/lib/python3.11/site-packages/lightning/pytorch/trainer/call.py", line 146, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/myuser/Matcha-TTS/matcha/models/baselightningmodule.py", line 186, in on_validation_end
    output = self.synthesise(x[:, :x_lengths], x_lengths, n_timesteps=10, spks=spks)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myuser/miniconda3/envs/Matcha-TTS/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/myuser/Matcha-TTS/matcha/models/matcha_tts.py", line 123, in synthesise
    y_mask = sequence_mask(y_lengths, y_max_length_).unsqueeze(1).to(x_mask.dtype)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myuser/Matcha-TTS/matcha/utils/model.py", line 10, in sequence_mask
    x = torch.arange(max_length, dtype=length.dtype, device=length.device)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: upper bound and larger bound inconsistent with step sign
[2023-10-17 17:35:25,849][matcha.utils.utils][INFO] - Output dir: /home/myuser/Matcha-TTS/outputs/2023-10-17/15-36-28
Error executing job with overrides: []
Traceback (most recent call last):
  File "/home/myuser/Matcha-TTS/matcha/train.py", line 122, in <module>
    main()  # pylint: disable=no-value-for-parameter
    ^^^^^^
  File "/home/myuser/miniconda3/envs/Matcha-TTS/lib/python3.11/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/home/myuser/miniconda3/envs/Matcha-TTS/lib/python3.11/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/home/myuser/miniconda3/envs/Matcha-TTS/lib/python3.11/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/home/myuser/miniconda3/envs/Matcha-TTS/lib/python3.11/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/home/myuser/miniconda3/envs/Matcha-TTS/lib/python3.11/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
           ^^^^^^
  File "/home/myuser/miniconda3/envs/Matcha-TTS/lib/python3.11/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
            ^^^^^^^^^^
  File "/home/myuser/miniconda3/envs/Matcha-TTS/lib/python3.11/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
        ^^^^^^^^^^^^^^^^
  File "/home/myuser/miniconda3/envs/Matcha-TTS/lib/python3.11/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/home/myuser/miniconda3/envs/Matcha-TTS/lib/python3.11/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myuser/Matcha-TTS/matcha/train.py", line 112, in main
    metric_dict, _ = train(cfg)
                     ^^^^^^^^^^
  File "/home/myuser/Matcha-TTS/matcha/utils/utils.py", line 86, in wrap
    raise ex
  File "/home/myuser/Matcha-TTS/matcha/utils/utils.py", line 76, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
                               ^^^^^^^^^^^^^^^^^^
  File "/home/myuser/Matcha-TTS/matcha/train.py", line 79, in train
    trainer.fit(model=model, datamodule=datamodule, ckpt_path=cfg.get("ckpt_path"))
  File "/home/myuser/miniconda3/envs/Matcha-TTS/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 532, in fit
    call._call_and_handle_interrupt(
  File "/home/myuser/miniconda3/envs/Matcha-TTS/lib/python3.11/site-packages/lightning/pytorch/trainer/call.py", line 43, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myuser/miniconda3/envs/Matcha-TTS/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 571, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/myuser/miniconda3/envs/Matcha-TTS/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 980, in _run
    results = self._run_stage()
              ^^^^^^^^^^^^^^^^^
  File "/home/myuser/miniconda3/envs/Matcha-TTS/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 1023, in _run_stage
    self.fit_loop.run()
  File "/home/myuser/miniconda3/envs/Matcha-TTS/lib/python3.11/site-packages/lightning/pytorch/loops/fit_loop.py", line 202, in run
    self.advance()
  File "/home/myuser/miniconda3/envs/Matcha-TTS/lib/python3.11/site-packages/lightning/pytorch/loops/fit_loop.py", line 355, in advance
    self.epoch_loop.run(self._data_fetcher)
  File "/home/myuser/miniconda3/envs/Matcha-TTS/lib/python3.11/site-packages/lightning/pytorch/loops/training_epoch_loop.py", line 134, in run
    self.on_advance_end()
  File "/home/myuser/miniconda3/envs/Matcha-TTS/lib/python3.11/site-packages/lightning/pytorch/loops/training_epoch_loop.py", line 249, in on_advance_end
    self.val_loop.run()
  File "/home/myuser/miniconda3/envs/Matcha-TTS/lib/python3.11/site-packages/lightning/pytorch/loops/utilities.py", line 181, in _decorator
    return loop_run(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myuser/miniconda3/envs/Matcha-TTS/lib/python3.11/site-packages/lightning/pytorch/loops/evaluation_loop.py", line 122, in run
    return self.on_run_end()
           ^^^^^^^^^^^^^^^^^
  File "/home/myuser/miniconda3/envs/Matcha-TTS/lib/python3.11/site-packages/lightning/pytorch/loops/evaluation_loop.py", line 258, in on_run_end
    self._on_evaluation_end()
  File "/home/myuser/miniconda3/envs/Matcha-TTS/lib/python3.11/site-packages/lightning/pytorch/loops/evaluation_loop.py", line 304, in _on_evaluation_end
    call._call_lightning_module_hook(trainer, hook_name, *args, **kwargs)
  File "/home/myuser/miniconda3/envs/Matcha-TTS/lib/python3.11/site-packages/lightning/pytorch/trainer/call.py", line 146, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/myuser/Matcha-TTS/matcha/models/baselightningmodule.py", line 186, in on_validation_end
    output = self.synthesise(x[:, :x_lengths], x_lengths, n_timesteps=10, spks=spks)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myuser/miniconda3/envs/Matcha-TTS/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/myuser/Matcha-TTS/matcha/models/matcha_tts.py", line 123, in synthesise
    y_mask = sequence_mask(y_lengths, y_max_length_).unsqueeze(1).to(x_mask.dtype)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myuser/Matcha-TTS/matcha/utils/model.py", line 10, in sequence_mask
    x = torch.arange(max_length, dtype=length.dtype, device=length.device)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: upper bound and larger bound inconsistent with step sign
```

**Comment by shivammehta25** [comment]
Hello, 

Do you have any validation set? It looks like something went wrong with the values of `y_max_length_` on line: 

https://github.com/shivammehta25/Matcha-TTS/blob/c8d0d60f87147fe340f4627b84588e812e5fbb00/matcha/models/matcha_tts.py#L120C21-L120C21

Could you print the value of `y_max_length_` and `y_max_length` ?

**Comment by eschmidbauer** [comment]
![image](https://github.com/shivammehta25/Matcha-TTS/assets/7139998/66ec4e49-8c9e-4812-9d5b-2ae810548f6c)
![Screenshot 2023-10-17 at 1 55 48 PM](https://github.com/shivammehta25/Matcha-TTS/assets/7139998/6148ca7d-900b-4f09-9c6c-2590761ecb34)

added a couple prints and re-ran.
i will have to wait for the training to run through to `23089` in order for it to throw the error.

**Comment by eschmidbauer** [comment]
![image](https://github.com/shivammehta25/Matcha-TTS/assets/7139998/229c4de4-7782-4973-b41b-3055fbe4ef00)
next step it crashed

**Comment by p0p4k** [comment]
can u restart the training on same dataset? nan values also does not look right.

**Comment by shivammehta25** [comment]
Also, the length values cannot be negative, it is the length of mel spectrogram. I suspect something is wrong somewhere else.

**Comment by eschmidbauer** [comment]
if i restart from training scratch, it will work fine. This seems to be an issue resuming training. 
Perhaps I am doing something incorrectly for resume. Are there documented steps on resuming?

**Comment by p0p4k** [comment]
add checkpoint path in train.py. It is quite possible your previous ckpt might have been corrupted or you changed something in your dataloader for the most recent run.

**Comment by eschmidbauer** [comment]
ok - i must have been overthinking things. i restarted training with just that param and it resumed properly :) 
Thanks for the help everyone !

**Comment by eschmidbauer** [comment]
Actually this problem did not go away, but i noticed about halfway through training, i see: `loss/train_step: nan`

![Screenshot 2023-10-19 at 2 01 13 PM](https://github.com/shivammehta25/Matcha-TTS/assets/7139998/d6202ec7-a8c7-4b0b-9324-7c4c15eed993)

**Comment by p0p4k** [comment]
your training data has some issue then. Iterate through it and check if every mel/wav file is valid. If issue still persists, try fp32 run.

**Comment by eschmidbauer** [comment]
thanks!

**Comment by eschmidbauer** [comment]
i started from scratch with same dataset and sure enough, it got to same epoch 83 and started showing `loss/train_step nan loss/val_step: nan loss/val_epoch nan loss/train_epoch: nan`

At end of Epoch 83, it crashed. 
If it is the dataset, why does it happen at epoch 83?

**Comment by p0p4k** [comment]
Cause the data loader uses a seed and it deterministically loads data pseudo randomly in the same sequence at each run

**Comment by eschmidbauer** [comment]
I restarted from scratch with a new dataset... now i see this error when running `matcha-data-stats`. I added some print statements to show what is happening... 
in `matcha/data/text/__init__.py`

```python
def text_to_sequence(text, cleaner_names):
    """Converts a string of text to a sequence of IDs corresponding to the symbols in the text.
    Args:
      text: string to convert to a sequence
      cleaner_names: names of the cleaner functions to run the text through
    Returns:
      List of integers corresponding to the symbols in the text
    """
    sequence = []

    clean_text = _clean_text(text, cleaner_names)
    for symbol in clean_text:
        if symbol not in _symbol_to_id:
            print(f"###{text}###{clean_text}###{type(symbol)}###{symbol}###")
        symbol_id = _symbol_to_id[symbol]
        sequence += [symbol_id]
    return sequence
```

```
matcha-data-stats -i mydataset.yaml -b 128 -f
  2%|█▉                                                                                                                   | 50/2930 [00:09<02:37, 18.24it/s]

###As we have said, the inspector, from discretion, and that he might not disturb the Abbe Faria's pupil in his researches, had seated himself in a corner, and was reading Le Drapeau Blanc.
###æz wiː hæv sˈɛd, ðɪ ɪnspˈɛktɚ, fɹʌm dɪskɹˈɛʃən, ænd ðæt hiː mˌaɪt nˌɑːt dɪstˈɜːb ðɪ ˈæb fˈɛɹɪəz pjˈuːpəl ɪn hɪz ɹɪsˈɜːtʃɪz, hæd sˈiːɾᵻd hɪmsˈɛlf ɪn ɐ kˈɔːɹnɚ, ænd wʌz ɹˈiːdɪŋ lə dɹˈeɪpaʊ blˈɑ̃nk.
###<class 'str'>###̃
######
Traceback (most recent call last):
  File "/home/myuser/miniconda3/envs/Matcha-TTS/bin/matcha-data-stats", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/myuser/Matcha-TTS/matcha/utils/generate_data_statistics.py", line 102, in main
    params = compute_data_statistics(data_loader, cfg["n_feats"])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myuser/Matcha-TTS/matcha/utils/generate_data_statistics.py", line 36, in compute_data_statistics
    for batch in tqdm(data_loader, leave=False):
  File "/home/myuser/miniconda3/envs/Matcha-TTS/lib/python3.11/site-packages/tqdm/std.py", line 1182, in __iter__
    for obj in iterable:
  File "/home/myuser/miniconda3/envs/Matcha-TTS/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "/home/myuser/miniconda3/envs/Matcha-TTS/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1325, in _next_data
    return self._process_data(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myuser/miniconda3/envs/Matcha-TTS/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/home/myuser/miniconda3/envs/Matcha-TTS/lib/python3.11/site-packages/torch/_utils.py", line 644, in reraise
    raise exception
KeyError: Caught KeyError in DataLoader worker process 18.
Original Traceback (most recent call last):
  File "/home/myuser/miniconda3/envs/Matcha-TTS/lib/python3.11/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/myuser/miniconda3/envs/Matcha-TTS/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myuser/miniconda3/envs/Matcha-TTS/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
            ~~~~~~~~~~~~^^^^^
  File "/home/myuser/Matcha-TTS/matcha/data/text_mel_datamodule.py", line 197, in __getitem__
    datapoint = self.get_datapoint(self.filepaths_and_text[index])
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myuser/Matcha-TTS/matcha/data/text_mel_datamodule.py", line 167, in get_datapoint
    text = self.get_text(text, add_blank=self.add_blank)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myuser/Matcha-TTS/matcha/data/text_mel_datamodule.py", line 190, in get_text
    text_norm = text_to_sequence(text, self.cleaners)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myuser/Matcha-TTS/matcha/text/__init__.py", line 25, in text_to_sequence
    symbol_id = _symbol_to_id[symbol]
                ~~~~~~~~~~~~~^^^^^^^^
KeyError: '̃'
```



To solve this I added a "continue" in there, not sure if that is appropriate 

```python
def text_to_sequence(text, cleaner_names):
    """Converts a string of text to a sequence of IDs corresponding to the symbols in the text.
    Args:
      text: string to convert to a sequence
      cleaner_names: names of the cleaner functions to run the text through
    Returns:
      List of integers corresponding to the symbols in the text
    """
    sequence = []

    clean_text = _clean_text(text, cleaner_names)
    for symbol in clean_text:
        if symbol not in _symbol_to_id:
            continue
        symbol_id = _symbol_to_id[symbol]
        sequence += [symbol_id]
    return sequence
```

**Comment by p0p4k** [comment]
Yeah that's right. You add extra vocab characters to symbol list or just continue like your solution.
