### ISSUE TITLE
training multi-gpu does not progress

### ISSUE THREAD

**Issue by eschmidbauer** [shivammehta25/Matcha-TTS#57]
When i start training with multi-gpu, the script hangs forever with GPU at 100% and GPU Memory at 2%. See screenshots and training command below.

![Screenshot 2024-02-13 at 1 40 45 PM](https://github.com/shivammehta25/Matcha-TTS/assets/7139998/c900cdf4-b09c-4420-a7e6-e5ec4491b780)
![Screenshot 2024-02-13 at 1 40 41 PM](https://github.com/shivammehta25/Matcha-TTS/assets/7139998/8b54e47c-22df-4027-bebe-e102c0c09ac2)

```python
export CUDA_VISIBLE_DEVICES=4,5
python matcha/train.py experiment=multispeaker trainer.devices=[0,1]
[2024-02-13 18:39:58,942][matcha.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2024-02-13 18:39:58,946][matcha.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
CONFIG
├── data
│   └── _target_: matcha.data.text_mel_datamodule.TextMelDataModule
│       name: multispeaker
│       train_filelist_path: data/filelists/multispeaker_audio_sid_text_train_filelist.txt
│       valid_filelist_path: data/filelists/multispeaker_audio_sid_text_val_filelist.txt
│       batch_size: 32
│       num_workers: 20
│       pin_memory: true
│       cleaners:
│       - english_cleaners2
│       add_blank: true
│       n_spks: 3
│       n_fft: 1024
│       n_feats: 80
│       sample_rate: 22050
│       hop_length: 256
│       win_length: 1024
│       f_min: 0
│       f_max: 8000
│       data_statistics:
│         mel_mean: -5.556468963623047
│         mel_std: 2.2946767807006836
│       seed: 1234
│
├── model
│   └── _target_: matcha.models.matcha_tts.MatchaTTS
│       n_vocab: 178
│       n_spks: 3
│       spk_emb_dim: 64
│       n_feats: 80
│       data_statistics:
│         mel_mean: -5.556468963623047
│         mel_std: 2.2946767807006836
│       out_size: null
│       prior_loss: true
│       encoder:
│         encoder_type: RoPE Encoder
│         encoder_params:
│           n_feats: 80
│           n_channels: 192
│           filter_channels: 768
│           filter_channels_dp: 256
│           n_heads: 2
│           n_layers: 6
│           kernel_size: 3
│           p_dropout: 0.1
│           spk_emb_dim: 64
│           n_spks: 1
│           prenet: true
│         duration_predictor_params:
│           filter_channels_dp: 256
│           kernel_size: 3
│           p_dropout: 0.1
│       decoder:
│         channels:
│         - 512
│         - 512
│         dropout: 0.05
│         attention_head_dim: 128
│         n_blocks: 1
│         num_mid_blocks: 2
│         num_heads: 2
│         act_fn: snakebeta
│       cfm:
│         name: CFM
│         solver: euler
│         sigma_min: 0.0001
│       optimizer:
│         _target_: torch.optim.Adam
│         _partial_: true
│         lr: 0.0001
│         weight_decay: 0.0
│
├── callbacks
│   └── model_checkpoint:
│         _target_: lightning.pytorch.callbacks.ModelCheckpoint
│         dirpath: /home/myuser/matcha-tts/Matcha-TTS/logs/train/multispeaker/runs/2024-02-13_18-39-58/checkpoints
│         filename: checkpoint_{epoch:03d}
│         monitor: epoch
│         verbose: false
│         save_last: true
│         save_top_k: 10
│         mode: max
│         auto_insert_metric_name: true
│         save_weights_only: false
│         every_n_train_steps: null
│         train_time_interval: null
│         every_n_epochs: 100
│         save_on_train_epoch_end: null
│       model_summary:
│         _target_: lightning.pytorch.callbacks.RichModelSummary
│         max_depth: 3
│       rich_progress_bar:
│         _target_: lightning.pytorch.callbacks.RichProgressBar
│
├── logger
│   └── tensorboard:
│         _target_: lightning.pytorch.loggers.tensorboard.TensorBoardLogger
│         save_dir: /home/myuser/matcha-tts/Matcha-TTS/logs/train/multispeaker/runs/2024-02-13_18-39-58/tensorboard/
│         name: null
│         log_graph: false
│         default_hp_metric: true
│         prefix: ''
│
├── trainer
│   └── _target_: lightning.pytorch.trainer.Trainer
│       default_root_dir: /home/myuser/matcha-tts/Matcha-TTS/logs/train/multispeaker/runs/2024-02-13_18-39-58
│       max_epochs: -1
│       accelerator: gpu
│       devices:
│       - 0
│       - 1
│       precision: 16-mixed
│       check_val_every_n_epoch: 1
│       deterministic: false
│       gradient_clip_val: 5.0
│
├── paths
│   └── root_dir: /home/myuser/matcha-tts/Matcha-TTS
│       data_dir: /home/myuser/matcha-tts/Matcha-TTS/data/
│       log_dir: /home/myuser/matcha-tts/Matcha-TTS/logs/
│       output_dir: /home/myuser/matcha-tts/Matcha-TTS/logs/train/multispeaker/runs/2024-02-13_18-39-58
│       work_dir: /home/myuser/matcha-tts/Matcha-TTS
│
├── extras
│   └── ignore_warnings: false
│       enforce_tags: true
│       print_config: true
│
├── task_name
│   └── train
├── run_name
│   └── multispeaker
├── tags
│   └── ['multispeaker']
├── train
│   └── True
├── test
│   └── True
├── ckpt_path
│   └── None
└── seed
    └── 1234
Seed set to 1234
[2024-02-13 18:39:58,991][__main__][INFO] - Instantiating datamodule <matcha.data.text_mel_datamodule.TextMelDataModule>
[2024-02-13 18:39:59,783][__main__][INFO] - Instantiating model <matcha.models.matcha_tts.MatchaTTS>

[2024-02-13 18:40:00,681][__main__][INFO] - Instantiating callbacks...
[2024-02-13 18:40:00,681][matcha.utils.instantiators][INFO] - Instantiating callback <lightning.pytorch.callbacks.ModelCheckpoint>
[2024-02-13 18:40:00,684][matcha.utils.instantiators][INFO] - Instantiating callback <lightning.pytorch.callbacks.RichModelSummary>
[2024-02-13 18:40:00,684][matcha.utils.instantiators][INFO] - Instantiating callback <lightning.pytorch.callbacks.RichProgressBar>
[2024-02-13 18:40:00,685][__main__][INFO] - Instantiating loggers...
[2024-02-13 18:40:00,685][matcha.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.tensorboard.TensorBoardLogger>
[2024-02-13 18:40:00,724][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
Using 16bit Automatic Mixed Precision (AMP)
Trainer already configured with model summary callbacks: [<class 'lightning.pytorch.callbacks.rich_model_summary.RichModelSummary'>]. Skipping setting a default `ModelSummary` callback.
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
[2024-02-13 18:40:00,949][__main__][INFO] - Logging hyperparameters!
[2024-02-13 18:40:00,988][__main__][INFO] - Starting training!
[rank: 0] Seed set to 1234
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/2

[rank: 1] Seed set to 1234
[rank: 1] Seed set to 1234
Initializing distributed: GLOBAL_RANK: 1, MEMBER: 2/2
----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All distributed processes registered. Starting with 2 processes
----------------------------------------------------------------------------------------------------

You are using a CUDA device ('NVIDIA GeForce RTX 3090') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision

```

**Comment by eschmidbauer** [comment]
i actually figured this out by setting `NCCL_P2P_LEVEL=NVL` before calling the `python matcha/train.py experiment=multispeaker trainer.devices=[0,1]`

**Comment by shivammehta25** [comment]
Hello, sorry for the delayed response.
I think this could also be because of a mismatch between CUDA drivers and torch binaries, try updating your cuda for native NCCL support. 

Regards,
Shivam

**Comment by eschmidbauer** [comment]
follow up on this -- 
i've found that I cannot train a single speaker model across multi-GPUs. just wondering if this is a known issue

```sh
export CUDA_VISIBLE_DEVICES=4,5
NCCL_P2P_LEVEL=NVL python matcha/train.py experiment=singlespeaker
[2024-02-21 18:48:37,707][matcha.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2024-02-21 18:48:37,711][matcha.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
CONFIG
├── data
│   └── _target_: matcha.data.text_mel_datamodule.TextMelDataModule
│       name: singlespeaker
│       train_filelist_path: data/filelists/singlespeaker_audio_sid_text_train_filelist.txt
│       valid_filelist_path: data/filelists/singlespeaker_audio_sid_text_val_filelist.txt
│       batch_size: 32
│       num_workers: 20
│       pin_memory: true
│       cleaners:
│       - english_cleaners2
│       add_blank: true
│       n_spks: 1
│       n_fft: 1024
│       n_feats: 80
│       sample_rate: 22050
│       hop_length: 256
│       win_length: 1024
│       f_min: 0
│       f_max: 8000
│       data_statistics:
│         mel_mean: -5.555796146392822
│         mel_std: 2.30115008354187
│       seed: 1234
│
├── model
│   └── _target_: matcha.models.matcha_tts.MatchaTTS
│       n_vocab: 178
│       n_spks: 1
│       spk_emb_dim: 64
│       n_feats: 80
│       data_statistics:
│         mel_mean: -5.555796146392822
│         mel_std: 2.30115008354187
│       out_size: null
│       prior_loss: true
│       encoder:
│         encoder_type: RoPE Encoder
│         encoder_params:
│           n_feats: 80
│           n_channels: 192
│           filter_channels: 768
│           filter_channels_dp: 256
│           n_heads: 2
│           n_layers: 6
│           kernel_size: 3
│           p_dropout: 0.1
│           spk_emb_dim: 64
│           n_spks: 1
│           prenet: true
│         duration_predictor_params:
│           filter_channels_dp: 256
│           kernel_size: 3
│           p_dropout: 0.1
│       decoder:
│         channels:
│         - 512
│         - 512
│         dropout: 0.05
│         attention_head_dim: 128
│         n_blocks: 1
│         num_mid_blocks: 2
│         num_heads: 2
│         act_fn: snakebeta
│       cfm:
│         name: CFM
│         solver: euler
│         sigma_min: 0.0001
│       optimizer:
│         _target_: torch.optim.Adam
│         _partial_: true
│         lr: 0.0001
│         weight_decay: 0.0
│
├── callbacks
│   └── model_checkpoint:
│         _target_: lightning.pytorch.callbacks.ModelCheckpoint
│         dirpath: matcha-tts/Matcha-TTS/logs/train/singlespeaker/runs/2024-02-21_18-48-37/checkpoints
│         filename: checkpoint_{epoch:03d}
│         monitor: epoch
│         verbose: true
│         save_last: true
│         save_top_k: 10
│         mode: max
│         auto_insert_metric_name: true
│         save_weights_only: false
│         every_n_train_steps: null
│         train_time_interval: null
│         every_n_epochs: 100
│         save_on_train_epoch_end: null
│       model_summary:
│         _target_: lightning.pytorch.callbacks.RichModelSummary
│         max_depth: 3
│       rich_progress_bar:
│         _target_: lightning.pytorch.callbacks.RichProgressBar
│
├── logger
│   └── tensorboard:
│         _target_: lightning.pytorch.loggers.tensorboard.TensorBoardLogger
│         save_dir: matcha-tts/Matcha-TTS/logs/train/singlespeaker/runs/2024-02-21_18-48-37/tensorboard/
│         name: null
│         log_graph: false
│         default_hp_metric: true
│         prefix: ''
│
├── trainer
│   └── _target_: lightning.pytorch.trainer.Trainer
│       default_root_dir: matcha-tts/Matcha-TTS/logs/train/singlespeaker/runs/2024-02-21_18-48-37
│       max_epochs: -1
│       accelerator: gpu
│       devices: auto
│       precision: 16-mixed
│       check_val_every_n_epoch: 1
│       deterministic: false
│       gradient_clip_val: 5.0
│       num_nodes: 1
│       sync_batchnorm: true
│
├── paths
│   └── root_dir: matcha-tts/Matcha-TTS
│       data_dir: matcha-tts/Matcha-TTS/data/
│       log_dir: matcha-tts/Matcha-TTS/logs/
│       output_dir: matcha-tts/Matcha-TTS/logs/train/singlespeaker/runs/2024-02-21_18-48-37
│       work_dir: matcha-tts/Matcha-TTS
│
├── extras
│   └── ignore_warnings: false
│       enforce_tags: true
│       print_config: true
│
├── task_name
│   └── train
├── run_name
│   └── singlespeaker
├── tags
│   └── ['singlespeaker']
├── train
│   └── True
├── test
│   └── True
├── ckpt_path
│   └── None
└── seed
    └── 1234
Seed set to 1234
[2024-02-21 18:48:37,755][__main__][INFO] - Instantiating datamodule <matcha.data.text_mel_datamodule.TextMelDataModule>
[2024-02-21 18:48:38,537][__main__][INFO] - Instantiating model <matcha.models.matcha_tts.MatchaTTS>
[2024-02-21 18:48:39,407][__main__][INFO] - Instantiating callbacks...
[2024-02-21 18:48:39,408][matcha.utils.instantiators][INFO] - Instantiating callback <lightning.pytorch.callbacks.ModelCheckpoint>
[2024-02-21 18:48:39,410][matcha.utils.instantiators][INFO] - Instantiating callback <lightning.pytorch.callbacks.RichModelSummary>
[2024-02-21 18:48:39,411][matcha.utils.instantiators][INFO] - Instantiating callback <lightning.pytorch.callbacks.RichProgressBar>
[2024-02-21 18:48:39,411][__main__][INFO] - Instantiating loggers...
[2024-02-21 18:48:39,411][matcha.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.tensorboard.TensorBoardLogger>
[2024-02-21 18:48:39,450][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
Using 16bit Automatic Mixed Precision (AMP)
Trainer already configured with model summary callbacks: [<class 'lightning.pytorch.callbacks.rich_model_summary.RichModelSummary'>]. Skipping setting a default `ModelSummary` callback.
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
[2024-02-21 18:48:39,662][__main__][INFO] - Logging hyperparameters!
[2024-02-21 18:48:39,701][__main__][INFO] - Starting training!
You are using a CUDA device ('NVIDIA GeForce RTX 3090') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
[rank: 0] Seed set to 1234
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/2
[rank: 1] Seed set to 1234
[rank: 1] Seed set to 1234
Initializing distributed: GLOBAL_RANK: 1, MEMBER: 2/2
----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All distributed processes registered. Starting with 2 processes
----------------------------------------------------------------------------------------------------

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [4,5]
LOCAL_RANK: 1 - CUDA_VISIBLE_DEVICES: [4,5]
┏━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┓
┃    ┃ Name                              ┃ Type              ┃ Params ┃
┡━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━┩
│ 0  │ encoder                           │ TextEncoder       │  7.2 M │
│ 1  │ encoder.emb                       │ Embedding         │ 34.2 K │
│ 2  │ encoder.prenet                    │ ConvReluNorm      │  591 K │
│ 3  │ encoder.prenet.conv_layers        │ ModuleList        │  553 K │
│ 4  │ encoder.prenet.norm_layers        │ ModuleList        │  1.2 K │
│ 5  │ encoder.prenet.relu_drop          │ Sequential        │      0 │
│ 6  │ encoder.prenet.proj               │ Conv1d            │ 37.1 K │
│ 7  │ encoder.encoder                   │ Encoder           │  6.2 M │
│ 8  │ encoder.encoder.drop              │ Dropout           │      0 │
│ 9  │ encoder.encoder.attn_layers       │ ModuleList        │  889 K │
│ 10 │ encoder.encoder.norm_layers_1     │ ModuleList        │  2.3 K │
│ 11 │ encoder.encoder.ffn_layers        │ ModuleList        │  5.3 M │
│ 12 │ encoder.encoder.norm_layers_2     │ ModuleList        │  2.3 K │
│ 13 │ encoder.proj_m                    │ Conv1d            │ 15.4 K │
│ 14 │ encoder.proj_w                    │ DurationPredictor │  345 K │
│ 15 │ encoder.proj_w.drop               │ Dropout           │      0 │
│ 16 │ encoder.proj_w.conv_1             │ Conv1d            │  147 K │
│ 17 │ encoder.proj_w.norm_1             │ LayerNorm         │    512 │
│ 18 │ encoder.proj_w.conv_2             │ Conv1d            │  196 K │
│ 19 │ encoder.proj_w.norm_2             │ LayerNorm         │    512 │
│ 20 │ encoder.proj_w.proj               │ Conv1d            │    257 │
│ 21 │ decoder                           │ CFM               │ 43.3 M │
│ 22 │ decoder.estimator                 │ Decoder           │ 43.3 M │
│ 23 │ decoder.estimator.time_embeddings │ SinusoidalPosEmb  │      0 │
│ 24 │ decoder.estimator.time_mlp        │ TimestepEmbedding │  4.5 M │
│ 25 │ decoder.estimator.down_blocks     │ ModuleList        │ 11.9 M │
│ 26 │ decoder.estimator.mid_blocks      │ ModuleList        │ 11.0 M │
│ 27 │ decoder.estimator.up_blocks       │ ModuleList        │ 15.0 M │
│ 28 │ decoder.estimator.final_block     │ Block1D           │  787 K │
│ 29 │ decoder.estimator.final_proj      │ Conv1d            │ 41.0 K │
└────┴───────────────────────────────────┴───────────────────┴────────┘
Trainable params: 50.4 M
Non-trainable params: 0
Total params: 50.4 M
Total estimated model params size (MB): 201
matcha-tts/venv/lib/python3.11/site-packages/lightning/pytorch/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we
found is 32. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
Epoch 0/-2 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/201 0:00:00 • -:--:-- 0.00it/s v_num: 0.000 loss/val_step: 5.954 loss/val_epoch: 6.061Error executing job with overrides: ['experiment=singlespeaker']
Traceback (most recent call last):
  File "matcha-tts/venv/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1133, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "miniconda3/lib/python3.11/queue.py", line 180, in get
    self.not_empty.wait(remaining)
  File "miniconda3/lib/python3.11/threading.py", line 324, in wait
    gotit = waiter.acquire(True, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "matcha-tts/venv/lib/python3.11/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 1773830) is killed by signal: Aborted.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "matcha-tts/Matcha-TTS/matcha/train.py", line 112, in main
    metric_dict, _ = train(cfg)
                     ^^^^^^^^^^
  File "matcha-tts/Matcha-TTS/matcha/utils/utils.py", line 86, in wrap
    raise ex
  File "matcha-tts/Matcha-TTS/matcha/utils/utils.py", line 76, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
                               ^^^^^^^^^^^^^^^^^^
  File "matcha-tts/Matcha-TTS/matcha/train.py", line 79, in train
    trainer.fit(model=model, datamodule=datamodule, ckpt_path=cfg.get("ckpt_path"))
  File "matcha-tts/venv/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 543, in fit
    call._call_and_handle_interrupt(
  File "matcha-tts/venv/lib/python3.11/site-packages/lightning/pytorch/trainer/call.py", line 43, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "matcha-tts/venv/lib/python3.11/site-packages/lightning/pytorch/strategies/launchers/subprocess_script.py", line 105, in launch
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "matcha-tts/venv/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 579, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "matcha-tts/venv/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 986, in _run
    results = self._run_stage()
              ^^^^^^^^^^^^^^^^^
  File "matcha-tts/venv/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 1032, in _run_stage
    self.fit_loop.run()
  File "matcha-tts/venv/lib/python3.11/site-packages/lightning/pytorch/loops/fit_loop.py", line 205, in run
    self.advance()
  File "matcha-tts/venv/lib/python3.11/site-packages/lightning/pytorch/loops/fit_loop.py", line 363, in advance
    self.epoch_loop.run(self._data_fetcher)
  File "matcha-tts/venv/lib/python3.11/site-packages/lightning/pytorch/loops/training_epoch_loop.py", line 138, in run
    self.advance(data_fetcher)
  File "matcha-tts/venv/lib/python3.11/site-packages/lightning/pytorch/loops/training_epoch_loop.py", line 204, in advance
    batch, _, __ = next(data_fetcher)
                   ^^^^^^^^^^^^^^^^^^
  File "matcha-tts/venv/lib/python3.11/site-packages/lightning/pytorch/loops/fetchers.py", line 133, in __next__
    batch = super().__next__()
            ^^^^^^^^^^^^^^^^^^
  File "matcha-tts/venv/lib/python3.11/site-packages/lightning/pytorch/loops/fetchers.py", line 60, in __next__
    batch = next(self.iterator)
            ^^^^^^^^^^^^^^^^^^^
  File "matcha-tts/venv/lib/python3.11/site-packages/lightning/pytorch/utilities/combined_loader.py", line 341, in __next__
    out = next(self._iterator)
          ^^^^^^^^^^^^^^^^^^^^
  File "matcha-tts/venv/lib/python3.11/site-packages/lightning/pytorch/utilities/combined_loader.py", line 78, in __next__
    out[i] = next(self.iterators[i])
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "matcha-tts/venv/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "matcha-tts/venv/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1329, in _next_data
    idx, data = self._get_data()
                ^^^^^^^^^^^^^^^^
  File "matcha-tts/venv/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1285, in _get_data
    success, data = self._try_get_data()
                    ^^^^^^^^^^^^^^^^^^^^
  File "matcha-tts/venv/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1146, in _try_get_data
    raise RuntimeError(f'DataLoader worker (pid(s) {pids_str}) exited unexpectedly') from e
RuntimeError: DataLoader worker (pid(s) 1773830, 1773832) exited unexpectedly

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
Exception in thread Thread-2 (_pin_memory_loop):
Traceback (most recent call last):
  File "miniconda3/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "miniconda3/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "matcha-tts/venv/lib/python3.11/site-packages/torch/utils/data/_utils/pin_memory.py", line 53, in _pin_memory_loop
    do_one_step()
  File "matcha-tts/venv/lib/python3.11/site-packages/torch/utils/data/_utils/pin_memory.py", line 30, in do_one_step
    r = in_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "miniconda3/lib/python3.11/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "matcha-tts/venv/lib/python3.11/site-packages/torch/multiprocessing/reductions.py", line 495, in rebuild_storage_fd
    fd = df.detach()
         ^^^^^^^^^^^
  File "miniconda3/lib/python3.11/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "miniconda3/lib/python3.11/multiprocessing/resource_sharer.py", line 86, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "miniconda3/lib/python3.11/multiprocessing/connection.py", line 507, in Client
    answer_challenge(c, authkey)
  File "miniconda3/lib/python3.11/multiprocessing/connection.py", line 751, in answer_challenge
    message = connection.recv_bytes(256)         # reject large message
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "miniconda3/lib/python3.11/multiprocessing/connection.py", line 215, in recv_bytes
    buf = self._recv_bytes(maxlength)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "miniconda3/lib/python3.11/multiprocessing/connection.py", line 413, in _recv_bytes
    buf = self._recv(4)
          ^^^^^^^^^^^^^
  File "miniconda3/lib/python3.11/multiprocessing/connection.py", line 382, in _recv
    raise EOFError
EOFError
[rank: 1] Child process with PID 1771899 terminated with code 1. Forcefully terminating all other processes to avoid zombies 🧟
Killed
```

**Comment by neils2019** [comment]
@eschmidbauer , had a similar issue with running training with GPU devices.  Was only able to train with CPU devices, however uncovered the issue with GPU runs -  Soln was to fix a versioning problem with the build environment.  Recreating my build virtual environment with cuda 12.1, and the following fixed the problem for me:

torch==2.0.1
torchaudio==2.0.2
torchcde==0.2.5
torchdiffeq==0.2.3
torchmetrics==1.1.1
torchsde==0.2.5
torchvision==0.15.2
lightning==2.0.0
# --------- hydra --------- #
hydra-core==1.3.2
hydra-colorlog==1.2.0
hydra-optuna-sweeper==1.2.0

![Screenshot 2024-wsl-matcha](https://github.com/shivammehta25/Matcha-TTS/assets/47200049/f99326e6-13af-4818-9c08-56283d3b51f6)

**Comment by shivammehta25** [comment]
Yes! I am sorry I haven't been able to update the dependencies due to other deadlines. However, this is probably just a dependency and driver mismatch. One other thing you can try is to try it in docker as contributed in this comment: https://github.com/shivammehta25/Matcha-TTS/issues/59#issuecomment-1966429853
