### ISSUE TITLE
gradio 4 removed `Box`

### ISSUE THREAD

**Issue by jimregan** [shivammehta25/Matcha-TTS#59]
```
Removing weight norm...
[+] hifigan_univ_v1 loaded!
Traceback (most recent call last):
  File "/usr/local/bin/matcha-tts-app", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/matcha/app.py", line 171, in main
    with gr.Box():
AttributeError: module 'gradio' has no attribute 'Box'
```

See: https://github.com/gradio-app/gradio/issues/6815

**Comment by jimregan** [comment]
FWIW, this is the Dockerfile I'm sending my students:

```
FROM ubuntu:22.04
RUN apt update
RUN apt install -y git python3-pip libsndfile1
RUN apt install -y automake autoconf libtool
RUN git clone https://github.com/rhasspy/espeak-ng && \
    cd espeak-ng && \
    bash autogen.sh && ./configure && make -j8 && make install && \
    ldconfig
RUN pip install git+https://github.com/shivammehta25/Matcha-TTS.git
RUN pip install gradio==3.48.0 # Breaks with gradio 4
CMD ["matcha-tts-app"]
```

(pinning the version works)

**Comment by shivammehta25** [comment]
I have to update the interface, for now downgrade gradio to => `gradio==3.43.2`

**Comment by shivammehta25** [comment]
I will keep it open for now to remember to update the interface post the deadline.

**Comment by jimregan** [comment]
I think the dockerfile is also kind of useful, as there are some things that aren't totally obvious (like the fork of the fork of espeak D:)
